"""Versioned domain contracts shared with StructAgent clients."""

from structagent_api.contracts.models import (
    ArtifactReference,
    ClassificationEvaluationResult,
    DatasetDescriptor,
    DefaultBinaryTaskDefinition,
    DefaultRegressionTaskDefinition,
    DefaultTaskCatalog,
    DefaultTaskDefinition,
    DraftReady,
    EvaluationResult,
    EvaluatorTruthPackage,
    MaterializationResult,
    MaterializedFileReference,
    ModelTaskPackage,
    NeedsClarification,
    RegressionEvaluationResult,
    RunRecord,
    TaskDraftOutcome,
    TaskDraftRequest,
    TaskSource,
    TaskSqlArtifact,
    TaskValidationReport,
)
from structagent_api.contracts.simulation import (
    SimulationRunResult,
    SimulationStudyArtifact,
)

__all__ = [
    "ArtifactReference",
    "ClassificationEvaluationResult",
    "DatasetDescriptor",
    "DefaultBinaryTaskDefinition",
    "DefaultRegressionTaskDefinition",
    "DefaultTaskCatalog",
    "DefaultTaskDefinition",
    "DraftReady",
    "EvaluationResult",
    "EvaluatorTruthPackage",
    "MaterializationResult",
    "MaterializedFileReference",
    "ModelTaskPackage",
    "NeedsClarification",
    "RegressionEvaluationResult",
    "RunRecord",
    "SimulationRunResult",
    "SimulationStudyArtifact",
    "TaskDraftOutcome",
    "TaskDraftRequest",
    "TaskSqlArtifact",
    "TaskSource",
    "TaskValidationReport",
]
